name: John Kurkowski
url: https://johnkurkowski.com
description: UX Engineer. Second, bolder self-assertion here.
kramdown:
  input: GFM
permalink: /posts/:title/
plugins:
  - jekyll-feed
  - jekyll-sitemap
sass:
  style: :compressed
