name: CI

on: [push, pull_request]

permissions:
  contents: read
  statuses: write

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version-file: '.nvmrc'

      - name: Install dependencies
        run: npm install

      - name: Test
        run: npm test

  visual-regression:
    if: github.event_name == 'pull_request' || github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    name: Lost Pixel

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version-file: '.nvmrc'

      - name: Install dependencies
        run: npm install

      - name: Build app
        run: npm run build

      - name: Start server (in background)
        run: npm run preview &

      - name: Lost Pixel
        uses: lost-pixel/lost-pixel@v3.22.0
        env:
          LOST_PIXEL_API_KEY: ${{ secrets.LOST_PIXEL_API_KEY }}

  deploy-production:
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    name: Deploy production
    needs: [test, visual-regression]

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version-file: '.nvmrc'

      - name: Install dependencies
        run: npm install

      - name: Build app
        run: npm run build

      - name: Deploy to Netlify
        run: >
          npx --yes netlify-cli deploy --prod --dir=dist --site
          "$NETLIFY_SITE_ID" --auth "$NETLIFY_AUTH_TOKEN"
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
